version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run: 
          command: |
            python3.8 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
        key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
        paths:
            - "venv"
  test:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pytest
      - store_artifacts:
          path: test-reports
          destination: test-reports
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test
